"""
alerts.py — Discord webhook + Gmail SMTP email alerts.

Secrets expected as environment variables:
  DISCORD_WEBHOOK_URL   — from your Discord server channel settings
  SMTP_USER             — your Gmail address
  SMTP_PASS             — Gmail App Password (not your real password)
  EMAIL_TO              — destination email address (can be same as SMTP_USER)
"""

import os
import smtplib
import requests
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText


# ─── Discord ──────────────────────────────────────────────────────────────────

DISCORD_COLOR = 0xf59e0b  # amber


def send_discord(articles: list[dict], topic_name: str):
    webhook_url = os.environ.get('DISCORD_WEBHOOK_URL')
    if not webhook_url:
        print("[discord] DISCORD_WEBHOOK_URL not set — skipping")
        return
    if not articles:
        return

    # Discord allows max 10 embeds per message; batch if needed
    for batch_start in range(0, len(articles), 10):
        batch = articles[batch_start:batch_start + 10]
        embeds = []
        for a in batch:
            embeds.append({
                "title": (a.get('title') or 'No title')[:256],
                "url": a.get('url', ''),
                "description": f"**Keyword:** `{a.get('keyword', '')}`\n{(a.get('description') or '')[:300]}",
                "color": DISCORD_COLOR,
                "footer": {"text": a.get('published', a.get('published date', ''))},
            })

        payload = {
            "username": "NewsWatch",
            "content": f"📰 **{topic_name}** — {len(articles)} new article(s)",
            "embeds": embeds,
        }

        try:
            r = requests.post(webhook_url, json=payload, timeout=15)
            r.raise_for_status()
            print(f"[discord] Sent batch of {len(batch)} for '{topic_name}'")
        except Exception as e:
            print(f"[discord] Error: {e}")


# ─── Email ────────────────────────────────────────────────────────────────────

def _build_email_html(articles: list[dict], topic_name: str) -> str:
    rows = ''.join(f'''
        <tr>
          <td style="padding:14px 0;border-bottom:1px solid #222;">
            <a href="{a.get('url', '')}"
               style="color:#f59e0b;text-decoration:none;font-weight:600;font-size:15px;line-height:1.4;">
              {a.get('title', 'No title')}
            </a><br>
            <span style="color:#888;font-size:12px;margin-top:4px;display:block;">
              {a.get('publisher', '')} &nbsp;·&nbsp;
              Keyword: <code style="background:#1e1e1e;padding:1px 5px;border-radius:3px;">
                {a.get('keyword', '')}
              </code> &nbsp;·&nbsp;
              {a.get('published', a.get('published date', ''))}
            </span>
            <p style="color:#aaa;font-size:13px;margin:6px 0 0;">
              {(a.get('description') or '')[:200]}
            </p>
          </td>
        </tr>
    ''' for a in articles)

    return f'''
    <html>
    <body style="margin:0;padding:0;background:#0a0a0a;font-family:-apple-system,sans-serif;">
      <div style="max-width:640px;margin:0 auto;padding:24px;">
        <div style="border-bottom:2px solid #f59e0b;padding-bottom:12px;margin-bottom:20px;">
          <span style="color:#f59e0b;font-size:11px;letter-spacing:2px;text-transform:uppercase;
                       font-weight:700;">NewsWatch Alert</span>
          <h1 style="color:#e8e8e8;margin:6px 0 0;font-size:22px;">{topic_name}</h1>
          <p style="color:#666;font-size:13px;margin:4px 0 0;">
            {len(articles)} new article(s) · {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}
          </p>
        </div>
        <table width="100%" cellpadding="0" cellspacing="0">{rows}</table>
        <p style="color:#333;font-size:11px;margin-top:24px;text-align:center;">
          NewsWatch · Auto-generated by GitHub Actions
        </p>
      </div>
    </body>
    </html>
    '''


def send_email(articles: list[dict], topic_name: str):
    smtp_user = os.environ.get('SMTP_USER')
    smtp_pass = os.environ.get('SMTP_PASS')
    email_to = os.environ.get('EMAIL_TO')

    if not all([smtp_user, smtp_pass, email_to]):
        print("[email] SMTP env vars not set — skipping")
        return
    if not articles:
        return

    subject = f"[NewsWatch] {topic_name} — {len(articles)} new article(s)"
    html = _build_email_html(articles, topic_name)

    msg = MIMEMultipart('alternative')
    msg['Subject'] = subject
    msg['From'] = f"NewsWatch <{smtp_user}>"
    msg['To'] = email_to
    msg.attach(MIMEText(html, 'html'))

    try:
        with smtplib.SMTP_SSL('smtp.gmail.com', 465, timeout=20) as server:
            server.login(smtp_user, smtp_pass)
            server.sendmail(smtp_user, email_to, msg.as_string())
        print(f"[email] Sent {len(articles)} articles for '{topic_name}' → {email_to}")
    except Exception as e:
        print(f"[email] Error: {e}")
